{{- if .Values.gateway.hostname }}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ include "common.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
{{ toYaml .Values.gateway.selector | indent 4 }}
  servers:
    - hosts:
        - {{ .Values.gateway.hostname }}
      port:
        name: http
        number: 80
        protocol: HTTP
      tls:
        httpsRedirect: true
    - hosts:
        - {{ .Values.gateway.hostname }}
      port:
        name: https
        number: 443
        protocol: HTTPS
      tls:
        credentialName: {{ .Values.gateway.tls.credentialName }}
        mode: {{ .Values.gateway.tls.mode }}
{{- end }}
